### PR TITLE
This seems bad. I think that user-defined domain is higher than envvar

### PR DESCRIPTION
**Pull request by kostasniktas**

### CODE REVIEW

**Comment by kostasniktas** [comment]
@atrocities 
@imawuman 

So... it _seems_ like we should take a user-defined domain over an environment variable.
1. DOMAIN OVERRIDE
2. TAGS
3. USER-DEFINED
4. BRANCH NAME (environment variable then 'git symbolic-ref HEAD`)
5. UNSPECIFIED

**Comment by imawuman** [comment]
+1

**Comment by atrocities** [comment]
Sounds good. Maybe split out #4 into 2 things just to make it more clear.

**Comment by kostasniktas** [comment]
1. DOMAIN OVERRIDE
2. TAGS
3. USER-DEFINED
4. BRANCH NAME via Build System Environment Variable
5. BRANCH NAME via 'git symbolic-ref HEAD'
6. UNSPECIFIED

**Pull request merged**
